### PR TITLE
Fix php 8 warnings

### LINKED ISSUE #2326: Warning: Undefined array key "id"
Contao: 4.13.6
Isotope: 2.8.5
PHP: 8.1.6

In debug modus, On a page with product list module, it shows this warning of undefined array key.

```
vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php:1029
```
Screenshot 2022-07-15 at 13 24 09

### PR DESCRIPTION
**Pull request by ameotoko**
Fixes #2326, #2334, #2335, #2336

### CODE REVIEW

File: system/modules/isotope/library/Isotope/Backend/Module/Callback.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function getSortingFields()
 
         foreach ($GLOBALS['TL_DCA']['tl_iso_product']['fields'] as $field => $arrData) {
             if ($arrData['attributes']['fe_sorting'] ?? false) {
-                $arrAttributes[$field] = \strlen($arrData['label'][0]) ? $arrData['label'][0] : $field;
+                $arrAttributes[$field] = \strlen($arrData['label'][0] ?? '') ? $arrData['label'][0] : $field;
```
Comment (aschempp) [inline system/modules/isotope/library/Isotope/Backend/Module/Callback.php]:
```suggestion
                $arrAttributes[$field] = $arrData['label'][0] ?? $field;
```

File: system/modules/isotope/library/Isotope/Model/Attribute/AbstractAttributeWithOptions.php [hunk 2]
```diff
@@ -325,7 +325,7 @@ public function generateValue($value, array $options = [])
     {
         $product = null;
 
-        if ($options['product'] instanceof IsotopeProduct) {
+        if (array_key_exists('product', $options) && $options['product'] instanceof IsotopeProduct) {
```
Comment (aschempp) [inline system/modules/isotope/library/Isotope/Model/Attribute/AbstractAttributeWithOptions.php]:
```suggestion
        if (($options['product'] ?? null) instanceof IsotopeProduct) {
```

File: system/modules/isotope/library/Isotope/Model/Product/AbstractProduct.php [hunk 3]
```diff
@@ -325,7 +325,7 @@ public function getCssClass()
         }
 
         $arrCSS = StringUtil::deserialize($this->cssID, true);
-        if ('' !== (string) $arrCSS[1]) {
+        if ('' !== ($arrCSS[1] ?? '')) {
```
Comment (aschempp) [inline system/modules/isotope/library/Isotope/Model/Product/AbstractProduct.php]:
```suggestion
        if (!empty($arrCSS[1])) {
```

File: system/modules/isotope/library/Isotope/Model/Product/Standard.php [hunk 4]
```diff
@@ -619,8 +619,8 @@ function (ProductActionInterface $action) use ($arrConfig) {
         $objTemplate->useQuantity = $arrConfig['useQuantity'] && null === $this->getCollectionItem();
         $objTemplate->minimum_quantity = $this->getMinimumQuantity();
         $objTemplate->raw = $this->arrData;
-        $objTemplate->raw_options = $this->getConfiguration();
-        $objTemplate->configuration = $this->getConfiguration();
+        $objTemplate->raw_options = $this->getOptions();
+        $objTemplate->configuration = $this->getOptions();
```
Comment (aschempp) [inline system/modules/isotope/library/Isotope/Model/Product/Standard.php]: why did you change this? Configuration and options is not the same (afair configuration is only for BC)

File: system/modules/isotope_reports/library/Isotope/Report/Sales.php [hunk 5]
```diff
@@ -35,19 +35,19 @@ protected function initializeDefaultValues()
         // Set default session data
         $arrSession = Session::getInstance()->get('iso_reports');
 
-        if ($arrSession[$this->name]['period'] == '') {
+        if (($arrSession[$this->name]['period'] ?? '') == '') {
```
Comment (aschempp) [inline system/modules/isotope_reports/library/Isotope/Report/Sales.php]:
```suggestion
        if (empty($arrSession[$this->name]['period'])) {
```

File: system/modules/isotope_reports/library/Isotope/Report/Sales.php [hunk 6]
```diff
@@ -35,19 +35,19 @@ protected function initializeDefaultValues()
...
             $arrSession[$this->name]['period'] = 'month';
         }
 
-        if ($arrSession[$this->name]['columns'] == '') {
+        if (($arrSession[$this->name]['columns'] ?? '') == '') {
```
Comment (aschempp) [inline system/modules/isotope_reports/library/Isotope/Report/Sales.php]:
```suggestion
        if (empty($arrSession[$this->name]['columns'])) {
```

File: system/modules/isotope_reports/library/Isotope/Report/Sales.php [hunk 7]
```diff
@@ -35,19 +35,19 @@ protected function initializeDefaultValues()
...
             $arrSession[$this->name]['columns'] = '6';
         }
 
-        if (!\in_array($arrSession[$this->name]['date_field'], ['locked', 'date_paid', 'date_shipped'], true)) {
+        if (!\in_array($arrSession[$this->name]['date_field'] ?? null, ['locked', 'date_paid', 'date_shipped'], true)) {
             $arrSession[$this->name]['date_field'] = 'locked';
         }
 
-        if ($arrSession[$this->name]['from'] == '') {
+        if (($arrSession[$this->name]['from'] ?? '') == '') {
```
Comment (aschempp) [inline system/modules/isotope_reports/library/Isotope/Report/Sales.php]:
```suggestion
        if (empty($arrSession[$this->name]['from'])) {
```

File: system/modules/isotope_reports/library/Isotope/Report/SalesProduct.php [hunk 8]
```diff
@@ -255,7 +255,7 @@ protected function initializeDefaultValues()
         $arrSession = Session::getInstance()->get('iso_reports')
         ;
 
-        if ($arrSession[$this->name]['tl_sort'] == '') {
+        if (($arrSession[$this->name]['tl_sort'] ?? '') == '') {
```
Comment (aschempp) [inline system/modules/isotope_reports/library/Isotope/Report/SalesProduct.php]:
```suggestion
        if (empty($arrSession[$this->name]['tl_sort'])) {
```

File: system/modules/isotope_reports/library/Isotope/Report/SalesTotal.php [hunk 9]
```diff
@@ -266,11 +266,11 @@ protected function initializeDefaultValues()
         // Set default session data
         $arrSession = Session::getInstance()->get('iso_reports');
 
-        if ($arrSession[$this->name]['period'] == '') {
+        if (($arrSession[$this->name]['period'] ?? '') == '') {
```
Comment (aschempp) [inline system/modules/isotope_reports/library/Isotope/Report/SalesTotal.php]:
```suggestion
        if (empty($arrSession[$this->name]['period'])) {
```

File: system/modules/isotope_reports/library/Isotope/Report/SalesTotal.php [hunk 10]
```diff
@@ -266,11 +266,11 @@ protected function initializeDefaultValues()
...
             $arrSession[$this->name]['period'] = 'month';
         }
 
-        if ($arrSession[$this->name]['stop'] == '') {
+        if (($arrSession[$this->name]['stop'] ?? '') == '') {
```
Comment (aschempp) [inline system/modules/isotope_reports/library/Isotope/Report/SalesTotal.php]:
```suggestion
        if (empty($arrSession[$this->name]['stop'])) {
```

File: system/modules/isotope_reports/library/Isotope/Report/SalesTotal.php [hunk 11]
```diff
@@ -283,7 +283,7 @@ protected function initializeDefaultValues()
             }
         }
 
-        if ($arrSession[$this->name]['start'] == '') {
+        if (($arrSession[$this->name]['start'] ?? '') == '') {
```
Comment (aschempp) [inline system/modules/isotope_reports/library/Isotope/Report/SalesTotal.php]:
```suggestion
        if (empty($arrSession[$this->name]['start'])) {
```

**Review by aschempp — CHANGES_REQUESTED** [review]
Thanks a lot @ameotoko!

Can you explain the configuration/options changes?

File: system/modules/isotope/library/Isotope/Model/Product/Standard.php (hunk 4 above)
Comment (ameotoko) [reply system/modules/isotope/library/Isotope/Model/Product/Standard.php]: Because it is suggested by PHPDoc 🤷🏻‍♂️

https://github.com/isotope/core/blob/175a07f4b3e84fcfee63d48f8eda91f8475cf512/system/modules/isotope/library/Isotope/Model/Product/Standard.php#L400-L402

**Comment by ameotoko** [comment]
I keep finding more of these while upgrading my Contao/Isotope instance. Should I open different issues/PRs, or just push to this one while it's open?

File: system/modules/isotope/library/Isotope/Model/Product/Standard.php (hunk 4 above)
Comment (aschempp) [reply system/modules/isotope/library/Isotope/Model/Product/Standard.php]: yes, you should not use the method itself. But they return different values, so we can't replace them in the default template data 🙃

**Comment by aschempp** [comment]
> I keep finding more of these while upgrading my Contao/Isotope instance. Should I open different issues/PRs, or just push to this one while it's open?

feel free to append while it's open, I tend to do the same (see https://github.com/contao/contao/pull/5016) 😂

File: system/modules/isotope/library/Isotope/Model/Product/Standard.php (hunk 4 above)
Comment (ameotoko) [reply system/modules/isotope/library/Isotope/Model/Product/Standard.php]: @aschempp ~~it's not me, Isotope itself uses it. I get more errors from other places where Isotope calls it BTW. So, deprecated method triggers errors, what do you suggest? 🤔~~

see [below](https://github.com/isotope/core/pull/2338#issuecomment-1205524279)

**Comment by ameotoko** [comment]
> yes, you should not use the method itself. But they return different values, so we can't replace them in the default template data 🙃

I've spent a litte more time now, and I was able to find the actual problem in `getConfiguration()`. This is now fixed in [73c55fd](https://github.com/isotope/core/pull/2338/commits/73c55fde8c4663e32b14d3c0b1da8eb3d34ee023), and the call to `getOptions()` is reverted back to `getConfiguration()`. @aschempp can you please review the change?

File: system/modules/isotope/library/Isotope/Model/ProductCollection.php [hunk 12]
```diff
@@ -1680,7 +1680,7 @@ protected function generateItem(ProductCollectionItem $objItem)
             'sku'               => $objItem->getSku(),
             'name'              => $objItem->getName(),
             'options'           => Isotope::formatOptions($objItem->getOptions()),
-            'configuration'     => $objItem->getConfiguration(),
+            'configuration'     => $objItem->getOptions(),
```
Comment (aschempp) [inline system/modules/isotope/library/Isotope/Model/ProductCollection.php]: This should be reverted too, right?

File: system/modules/isotope/library/Isotope/Module/ProductList.php [hunk 13]
```diff
@@ -151,7 +151,7 @@ protected function compile()
         if (!\is_array($arrProducts)) {
             // Display "loading products" message and add cache flag
             if ($this->blnCacheProducts) {
-                $blnCacheMessage = (bool) $this->iso_productcache[$cacheKey];
+                $blnCacheMessage = $this->iso_productcache[$cacheKey] ?? false;
```
Comment (aschempp) [inline system/modules/isotope/library/Isotope/Module/ProductList.php:154]: I think we should keep the boolean casting

**Review by aschempp — CHANGES_REQUESTED** [review]
Thanks a lot! Just a minor nitpick left 🙃

File: system/modules/isotope/library/Isotope/Module/ProductList.php (hunk 13 above)
Comment (ameotoko) [reply system/modules/isotope/library/Isotope/Module/ProductList.php:154]: Sure, why not, but isn't `iso_productcache` always an array of boolean values anyway? Also, `$blnCacheMessage` is only used in `if` statement, which casts it to bool automatically.

File: system/modules/isotope/library/Isotope/Model/ProductCollection.php (hunk 12 above)
Comment (ameotoko) [reply system/modules/isotope/library/Isotope/Model/ProductCollection.php]: Yep, I forgot. Reverted in 593f635f

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
Thank you @ameotoko
