### PR TITLE
Fix displaying and validating subdivisions with subgroups

### LINKED ISSUE #1678: Subdivisions with subgroups not validating or displaying properly.
When using some subdivisions (GB is the best example) which have another dimension to their array (for sub-subdivisons), the validation on checkout does not let a user proceed. (Invalid Input).

I see that this may be an issue in the FormConditionalSelect menu, as there is a custom isValidOption on ConditionalSelect which seems to clear up that issue, but that still leaves the issue where in `Isotope\Model\Address` line 198 there is still not a check for another dimension in the array.

### PR DESCRIPTION
**Pull request by qzminski**
Fixes #1678

### CODE REVIEW

File: system/modules/isotope/library/Isotope/Model/Address.php [hunk 1]
```diff
@@ -203,7 +203,21 @@ public function getTokens($arrFields = null)
...
+                    // Support multi-dimensional arrays (e.g. subdivisions of United Kingdom)
+                    if (is_array($v)) {
+                        foreach ($v as $vv) {
+                            if ($vv[$this->subdivision]) {
+                                $arrTokens['subdivision'] = $vv[$this->subdivision];
+                                break;
+                            }
+                        }
+                    } else {
+                        $arrTokens['subdivision'] = $arrSubdivisions[strtolower($country)][$this->subdivision];
```
Comment (aschempp) [inline system/modules/isotope/library/Isotope/Model/Address.php]: This can't be right. We're `foreach`ing the array but then not use any of it's foreach-value in the loop? 

Did you test this? On the first spot it seems wrong to have two `foreach`?

Comment (qzminski) [inline system/modules/isotope/library/Isotope/Model/Address.php]: I have tested it and it works as expected. We are using the foreach-value in the loop, see ```$v``` on line 209. If that is not an array on the other hand, then the loop is immediately broke in 217.
